//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empty_stock
    {
        public string id { get; set; }
        public Nullable<int> openingstock { get; set; }
        public Nullable<int> empty_received { get; set; }
        public Nullable<int> plastic_recieved { get; set; }
        public Nullable<int> backload { get; set; }
        public string notes { get; set; }
        public string insertuser { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
    
        public virtual useraccount useraccount { get; set; }
    }
}
