//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expensi
    {
        public string id { get; set; }
        public string head { get; set; }
        public string description { get; set; }
        public string amount { get; set; }
        public string accountant { get; set; }
        public string cashier { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public Nullable<System.DateTime> paymentdate { get; set; }
        public string paymenttype { get; set; }
        public string expensistype { get; set; }
    
        public virtual useraccount useraccount { get; set; }
        public virtual useraccount useraccount1 { get; set; }
    }
}
