//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesmenledger
    {
        public string id { get; set; }
        public string salesmanid { get; set; }
        public string item { get; set; }
        public Nullable<int> openingstock { get; set; }
        public Nullable<int> stockreceived { get; set; }
        public Nullable<int> additionalstock { get; set; }
        public Nullable<int> totalstock { get; set; }
        public Nullable<int> soldstock { get; set; }
        public Nullable<int> stockreturned { get; set; }
        public Nullable<int> emptiesreturned { get; set; }
        public string empties_owings { get; set; }
        public string store_attendant { get; set; }
        public string remarks { get; set; }
        public string cash_taken { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string store_keeper { get; set; }
        public string Receipt_no { get; set; }
        public string approved_by { get; set; }
        public string cashier { get; set; }
        public string week { get; set; }
        public string store_supervisor { get; set; }
        public string recoreded_by { get; set; }
    
        public virtual salesman salesman { get; set; }
    }
}
