//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHIMEX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chimexerpEntities : DbContext
    {
        public chimexerpEntities()
            : base("name=chimexerpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balance> Balances { get; set; }
        public virtual DbSet<BankDeposit> BankDeposits { get; set; }
        public virtual DbSet<bonu> bonus { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<customer_ledger> customer_ledger { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<deduction> deductions { get; set; }
        public virtual DbSet<Empties_Backload> Empties_Backload { get; set; }
        public virtual DbSet<EmptiesReceived> EmptiesReceiveds { get; set; }
        public virtual DbSet<empty_stock> empty_stock { get; set; }
        public virtual DbSet<Emptytype> Emptytypes { get; set; }
        public virtual DbSet<EspectedEmpty> EspectedEmpties { get; set; }
        public virtual DbSet<Expensi> Expensis { get; set; }
        public virtual DbSet<larstock_added> larstock_added { get; set; }
        public virtual DbSet<Larstock> Larstocks { get; set; }
        public virtual DbSet<main_stocks> main_stocks { get; set; }
        public virtual DbSet<main_stocks_Report> main_stocks_Report { get; set; }
        public virtual DbSet<main_stocks_Report_temp> main_stocks_Report_temp { get; set; }
        public virtual DbSet<order_cart> order_cart { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<paymentvoucher> paymentvouchers { get; set; }
        public virtual DbSet<production> productions { get; set; }
        public virtual DbSet<production_log> production_log { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<salarybatch> salarybatches { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<sales_canceled> sales_canceled { get; set; }
        public virtual DbSet<salesman> salesmen { get; set; }
        public virtual DbSet<salesmenledger> salesmenledgers { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<stock_complain> stock_complain { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<stocks_added> stocks_added { get; set; }
        public virtual DbSet<stocks_closing> stocks_closing { get; set; }
        public virtual DbSet<stocks_opening> stocks_opening { get; set; }
        public virtual DbSet<supply> supplies { get; set; }
        public virtual DbSet<supplies_temp> supplies_temp { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<useraccount> useraccounts { get; set; }
    }
}
