//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHIMEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deduction
    {
        public string id { get; set; }
        public string staffid { get; set; }
        public Nullable<decimal> item { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public string status { get; set; }
        public string decription { get; set; }
        public string batchid { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual salarybatch salarybatch { get; set; }
    }
}
