//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHIMEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class production
    {
        public string id { get; set; }
        public string name { get; set; }
        public string decription { get; set; }
        public Nullable<int> qty_bags { get; set; }
        public Nullable<int> qty_items { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public string insertuser { get; set; }
        public string stockid { get; set; }
    
        public virtual useraccount useraccount { get; set; }
        public virtual stock stock { get; set; }
    }
}
